### ISSUE TITLE
Pre/post scripts

### ISSUE THREAD

**Issue by shaunwarman** [blacklabelops/logrotate#22]
How would one go about sending a signal from one container process to another container process?

For nginx, the worker needs to be gracefully restarted to remove the file handle on the log files via something like:
```
postrotate
  [ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`
endscript
```

But, as a sidecar, how would you do this without exposing the docker control socket?

**Comment by blacklabelops** [comment]
I just recently found this: https://github.com/msoap/shell2http

You can write scripts inside your nginx image and then expose the commands as http endpoints.

**Comment by shaunwarman** [comment]
Awesome! This is really cool.

**Comment by franck-grenier** [comment]
Hello blacklabelops,
your logrotate image is really cool ! Nice work !

I'm bringing up this issue because I need to rotate custom logs written by my Nginx container.

I had a look at https://github.com/msoap/shell2http. Quite practical but it does not fit with my Nginx container as it would start another process beside Nginx.

Do you have another solution to make the logrotate container send a signal to the Nginx container ?
